# Generated by Django 2.1.2 on 2018-10-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=400)),
            ],
        ),
    ]
